#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x workspace > /dev/null || workspace &
pgrep -x bluebar > /dev/null || bluebar &

picom &
dunst &
unclutter --timeout 10 &
hsetroot -center ~/Bilder/wallpaper.png &

bspc monitor -d          

bspc config top_padding         35
bspc config border_width         1
bspc config focused_border_color "#e91e63"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
